In [1]:
import pickle
import pandas as pd
import networkx as nx
import pennylane as qml
from pennylane import numpy as np

In [2]:
data = []

In [3]:
for idx in range(1, 10):
    data_point = []
    hypergraph_name = f"email-Enron_{idx}"
    data_point.append(hypergraph_name)
    print(f"Current graph: {hypergraph_name}")
    with open(f'results/max_cut_{hypergraph_name}.pkl', 'rb') as f:
        results = pickle.load(f)
    print("Best fair cut objective: ", results[0])
    data_point.append(results[0])
    with open(f'results/fair_cut_{hypergraph_name}.pkl', 'rb') as f:
        results = pickle.load(f)
    print("Best max cut objective: ", results[0])
    data_point.append(results[0])
    data.append(data_point)

Current graph: email-Enron_1
Best fair cut objective:  19.416666666666664
Best max cut objective:  -0.5298073997491423
Current graph: email-Enron_2
Best fair cut objective:  57.016275510204075
Best max cut objective:  -0.5103543924095161
Current graph: email-Enron_3
Best fair cut objective:  143.63333333333333
Best max cut objective:  -0.5060599835184342
Current graph: email-Enron_4
Best fair cut objective:  6.75
Best max cut objective:  -0.5593568537288068
Current graph: email-Enron_5
Best fair cut objective:  59.61737654320988
Best max cut objective:  -0.5102560988510098
Current graph: email-Enron_6
Best fair cut objective:  116.9423261839171
Best max cut objective:  -0.506197979597538
Current graph: email-Enron_7
Best fair cut objective:  85.58502393550012
Best max cut objective:  -0.5103895996729707
Current graph: email-Enron_8
Best fair cut objective:  56.08666666666667
Best max cut objective:  -0.5133281948928191
Current graph: email-Enron_9
Best fair cut objective:  154.17966364

In [4]:
for idx in range(1, 21):
    data_point = []
    hypergraph_name = f"contact-high-school_{idx}"
    data_point.append(hypergraph_name)
    print(f"Current graph: {hypergraph_name}")
    with open(f'results/max_cut_{hypergraph_name}.pkl', 'rb') as f:
        results = pickle.load(f)
    print("Best fair cut objective: ", results[0])
    data_point.append(results[0])
    with open(f'results/fair_cut_{hypergraph_name}.pkl', 'rb') as f:
        results = pickle.load(f)
    print("Best max cut objective: ", results[0])
    data_point.append(results[0])
    data.append(data_point)

Current graph: contact-high-school_1
Best fair cut objective:  91.83333333333334
Best max cut objective:  -0.5131833565700609
Current graph: contact-high-school_2
Best fair cut objective:  102.83333333333331
Best max cut objective:  -0.509989711269506
Current graph: contact-high-school_3
Best fair cut objective:  14.88888888888889
Best max cut objective:  -0.5350136991238387
Current graph: contact-high-school_4
Best fair cut objective:  141.22222222222226
Best max cut objective:  -0.5082269112126224
Current graph: contact-high-school_5
Best fair cut objective:  67.08333333333333
Best max cut objective:  -0.513653090950347
Current graph: contact-high-school_6
Best fair cut objective:  132.0277777777778
Best max cut objective:  -0.508841466794262
Current graph: contact-high-school_7
Best fair cut objective:  74.77777777777777
Best max cut objective:  -0.5137008776057265
Current graph: contact-high-school_8
Best fair cut objective:  23.555555555555557
Best max cut objective:  -0.525715030

In [5]:
df = pd.DataFrame(data, columns=['f', 'quantum max', 'quantum fair'])

In [7]:
from datetime import datetime
now = datetime.now()
dt_string = now.strftime("%Y-%m-%d_%H-%M-%S")
print(dt_string)  

2026-04-03_13-00-01


In [8]:
df.to_csv(f'{dt_string}_quantum.csv')

In [2]:
P = np.load('/work/acslab/users/baobach/quantum_hypergraph/QuantumHypergraphPartitioning/data/contact-high-school/numpy/contact-high-school_1.npy')

In [3]:
M = P@P.transpose()

In [4]:
one_vector = np.ones((P.shape[1], 1))

In [5]:
V = np.zeros((P.shape[0], P.shape[0]))
np.fill_diagonal(V, P@one_vector)

In [6]:
V = V - M

In [7]:
V

tensor([[ 6.22916667, -0.99305556, -0.42361111,  0.        , -0.42361111,
         -0.47222222, -0.25      , -0.36111111, -0.25      , -0.64583333,
         -0.58333333, -0.47222222,  0.        , -1.10416667, -0.25      ],
        [-0.99305556,  7.52777778, -0.64583333, -0.25      , -0.53472222,
         -0.47222222, -0.42361111,  0.        , -0.42361111, -0.86805556,
         -0.80555556, -0.25      , -0.58333333, -1.27777778,  0.        ],
        [-0.42361111, -0.64583333,  4.99305556, -0.25      , -0.25      ,
         -0.36111111, -0.25      , -0.36111111, -0.25      , -0.36111111,
         -0.47222222, -0.47222222,  0.        , -0.64583333, -0.25      ],
        [ 0.        , -0.25      , -0.25      ,  3.79861111, -0.47222222,
         -0.3125    , -0.53472222, -0.47222222, -0.47222222,  0.        ,
          0.        , -0.36111111, -0.42361111, -0.25      ,  0.        ],
        [-0.42361111, -0.53472222, -0.25      , -0.47222222,  4.04861111,
         -0.36111111, -0.25      ,

In [12]:
import numpy as np

def augment_with_diagonal(A):
    A = np.asarray(A)
    d = np.diag(A)
    A_prime = np.block([
        [A, d[:, None]],
        [d[None, :], np.array([[0]])]
    ])
    np.fill_diagonal(A_prime, 0.0)
    return A_prime

In [13]:
a = augment_with_diagonal(V)

In [14]:
a

array([[ 0.        , -0.99305556, -0.42361111,  0.        , -0.42361111,
        -0.47222222, -0.25      , -0.36111111, -0.25      , -0.64583333,
        -0.58333333, -0.47222222,  0.        , -1.10416667, -0.25      ,
         6.22916667],
       [-0.99305556,  0.        , -0.64583333, -0.25      , -0.53472222,
        -0.47222222, -0.42361111,  0.        , -0.42361111, -0.86805556,
        -0.80555556, -0.25      , -0.58333333, -1.27777778,  0.        ,
         7.52777778],
       [-0.42361111, -0.64583333,  0.        , -0.25      , -0.25      ,
        -0.36111111, -0.25      , -0.36111111, -0.25      , -0.36111111,
        -0.47222222, -0.47222222,  0.        , -0.64583333, -0.25      ,
         4.99305556],
       [ 0.        , -0.25      , -0.25      ,  0.        , -0.47222222,
        -0.3125    , -0.53472222, -0.47222222, -0.47222222,  0.        ,
         0.        , -0.36111111, -0.42361111, -0.25      ,  0.        ,
         3.79861111],
       [-0.42361111, -0.53472222, -0

In [46]:
diag_V

tensor([6.22916667, 7.52777778, 4.99305556, 3.79861111, 4.04861111,
        6.19444444, 5.9375    , 2.61111111, 5.6875    , 3.74305556,
        4.75      , 4.36111111, 5.5       , 7.08333333, 3.45138889], requires_grad=True)

In [28]:
Vlist = [np.diag(P[:, i]) - P[:, i].reshape(P.shape[0], 1) * P[:, i].reshape(1, P.shape[0]) for i in range(P.shape[1])]

In [29]:
max_p min_e E_{x \sim p}[x^* V_e x]

tensor([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        

In [43]:
set(np.where(Vlist[0] != 0.0)[1])

{3, 4}

In [37]:
Vlist[0]

tensor([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
        

In [30]:
Vlist

[tensor([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.25, -0.25,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  , -0.25,  0.25,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ],
         [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
           0.  ,  0.  ,  0.  ,  0.  ,  0.  , 

In [20]:
for i in range(Vlist[0].shape[0]):
    print(Vlist[0][i, :])

[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.    0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25  0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]
[ 0.    0.    0.   -0.25 -0.25  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.  ]

In [7]:
V.shape

(15, 15)

In [12]:
num_samples = 50
values = []
for sample_idx in range(num_samples):
    array = np.random.choice([-1, 1], size=V.shape[0], p=[0.5, 0.5])
    values.append(array@V@array.transpose())

In [13]:
print(np.max(values))

89.91666666666669


In [8]:
def max_cut_from_Q(Q, 
                   seed: int,
                   num_layers: int,
                   scaling_constant: float,
                   step_size: float, 
                   max_trials: int,
                   threshold: float,
                   #non_improving_steps: int
                  ):
    rng = np.random.default_rng(seed=seed)
    n_wires = Q.shape[0] + 1
    triu_indices = np.triu_indices(Q.shape[0])
    edge_list = []
    for (u, v) in zip(triu_indices[0], triu_indices[1]):
        if Q[u][v] == 0.0:
            continue
        else:
            if u == v:
                edge_list.append((0, n_wires - 1))
            else:
                edge_list.append((u, v))
    beta_params = scaling_constant * rng.random([1, num_layers], requires_grad=True)
    gamma_params = scaling_constant * rng.random([1, num_layers], requires_grad=True)
    print(beta_params)
    def U_B(beta):
        for wire in range(n_wires):
            qml.RX(2 * beta[0], wires=wire)
    def U_C(gamma):
        for u, v in edge_list: 
            w  = Q[u][u] if v == (n_wires - 1) else Q[u][v]
            qml.CNOT(wires=(u, v))
            qml.RZ(-w * gamma[0], wires=v)
            qml.CNOT(wires=(u, v))
    dev = qml.device('lightning.qubit', wires=n_wires)
    @qml.qnode(dev)
    def circuit(gammas, betas):
        for wire in range(n_wires):
            qml.Hadamard(wires=wire)
        for k in range(num_layers):
            U_C(gammas[:, k])
            U_B(betas[:, k])
        return [qml.expval(qml.PauliZ(u) @ qml.PauliZ(v)) for u, v in edge_list]
    def objective(gammas, betas):
        expectation_values = circuit(gammas, betas)
        expectation_values = np.array(expectation_values)
        expectation_values = (1/2)*(1-expectation_values)
        return -np.sum(expectation_values)

    opt = qml.AdamOptimizer(stepsize=step_size)
    objective_list = [objective(gamma_params, beta_params)]
    params_list = [(gamma_params, beta_params)]
    for i in range(max_trials):
        (gamma_params, beta_params), current_obj = opt.step_and_cost(objective, gamma_params, beta_params)
        if (i + 1) % 5 == 0:
            print("Current obj: ", current_obj)
            if np.abs(current_obj - objective_list[-1]) <= threshold:
                objective_list.append(current_obj)
                params_list.append((gamma_params, beta_params))
                break
        objective_list.append(current_obj)
        params_list.append((gamma_params, beta_params))
    result = [objective_list, params_list]
    best_params.append(result[1][np.argmin(result[0])])
    best_qaoa_objective = np.min(result[0])
    return best_params, best_qaoa_objective, result

In [9]:
step_size = 1e-2
threshold = 1e-8
max_trials = 500
scaling_constant = 5e-2

In [ ]:
best_params, best_qaoa_objective, result  =  max_cut_from_Q(Q = V, 
                                                            seed = 42,
                                                            num_layers = 2,
                                                            scaling_constant = scaling_constant,
                                                            step_size = step_size, 
                                                            max_trials = max_trials,
                                                            threshold = threshold)

[[0.0386978  0.02194392]]
Current obj:  -51.065115567314926
Current obj:  -52.859928402103506
Current obj:  -54.23718563091491
Current obj:  -55.08286863130717
Current obj:  -55.120460240252996
Current obj:  -55.06066745053252
Current obj:  -55.05423859801171
Current obj:  -55.07990435742401
Current obj:  -55.12191868943031
Current obj:  -55.1758516132076
Current obj:  -55.24269762726358
Current obj:  -55.324754935119444
Current obj:  -55.4126655642808
Current obj:  -55.48312619180297
Current obj:  -55.540269379610166
Current obj:  -55.61254841457716
Current obj:  -55.695372523352944
Current obj:  -55.77982623390045
Current obj:  -55.86745625553575
Current obj:  -55.962978041139465
Current obj:  -56.06195238343619
Current obj:  -56.16364740204324
Current obj:  -56.265987677356485
Current obj:  -56.341267521367854
Current obj:  -56.471690316224155
Current obj:  -56.61212248363629
Current obj:  -56.75161357004705
Current obj:  -56.9120656026663
Current obj:  -57.08787035126572
Current ob

In [ ]:
#def get_Q_max_variance(Q, num_samples, best_params):
n_wires = Q.shape[0] + 1
best_gammas, best_betas = best_params
dev = qml.device('lightning.qubit', wires=n_wires)
@qml.set_shots(shots = num_samples)
@qml.qnode(dev)
def circuit(gammas, betas):
    for wire in range(n_wires):
        qml.Hadamard(wires=wire)
    for k in range(num_layers):
        U_C(gammas[:, k])
        U_B(betas[:, k])
    return qml.sample()
samples = circuit(best_gammas, best_betas)
values = []
for sample in samples:
    new_x = np.array([(sample[i] + sample[len(sample) - 1]) % 2 for i in range(len(sample) - 1)])
    values.append(new_x@Q@new_x.transpose())
print("Best objective:", np.max(values))

In [ ]:
# dev = qml.device('lightning.qubit', wires=n_wires)
# @qml.qnode(dev)
# def circuit(gammas, betas):
#     for wire in range(n_wires):
#         qml.Hadamard(wires=wire)
#     for k in range(num_layers):
#         U_C(gammas[:, k])
#         U_B(betas[:, k])
#     return qml.sample()